1. Challenge 1:

- Answer: b
- Explanation: because the first log is called inside the function where foo = xyz. The second log is called outside but since the function was already declared outside too, it changes foo to xyz.

2. Challenge 2:

- Answer: a
- Explanation: same reason as before

3. Challenge 3:

- Answer: c
- Explanation: It's just logging a string wether it's part of a function or not, so it doesn't matter if the function was declared after being invoked.

4. Challenge 4:

- Answer: c
- Explanation: { num: 90 } because the value was changed to 90 before logging.

5. Bonus - Challenge 5:

- Answer: a
- Explanation: the first one is the original Bob and the second one calls the function where it's modified to Ada
